### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by CampanelliEmanuele** [CampanelliEmanuele/MNKGame#1]
Da fare prima della consegna
- [ ] Sistemare il codice affinché funzioni anche per grosse griglie
- [ ] Capire quali pezzi di codici possono essere scartati e quali riutilizzati

**Comment by sbizz97** [comment]
vdsvdvzdv

**Comment by CampanelliEmanuele** [comment]
- [ ] g
- [ ] g
- [ ] g
- [ ] l

**Comment by sbizz97** [comment]
- [ ] ku,jh,hmh

**Comment by CampanelliEmanuele** [comment]
Da fare prima della consegna
- [ ] Sistemare il codice affinché funzioni anche per grosse griglie
- [ ] Capire quali pezzi di codici possono essere scartati e quali riutilizzati
